[package]
name = "rockslide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = [ "tracing" ] }
base64 = "0.21.5"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = [ "rt-multi-thread", "macros" ] }
tower-http = { version = "0.3.5", features = [ "trace" ] }
tracing-subscriber = { version = "0.3.18", features = [ "env-filter" ] }
