# Rockslide configuration file.
#
# Any option or section can be omitted, causing defaults to be used.

[rockslide]
# Master access key, the only authentication used by rockslide. This key allows access to
# everything, including the registry. If not set, any priviledged access is disabled.
# master_key = "put-a-random-long-secret-key-here"

# Log level. Defaults to "rockslide=info", below is an example for more detailed insights similar
# to "classic" web server logs.
# log = "rockslide=debug,tower_http=debug,axum::rejection=trace"
log = "trace"

[registry]
# The storage path for the registry. If unset, defaults to the relative path "rockslide-storage",
# can be set to an absolute path as well.
storage_path = "/var/lib/rockslide/registry"

[containers]
# Path to the podman binary. If unset, defaults to "podman", which is looked up in $PATH.
podman_path = "/usr/bin/podman"
